#!/bin/bash
DOCKER_TAG="$1"
BASEDIR=$(dirname "$0")
if [ -z "$DOCKER_TAG" ]
then
    echo "Docker Image Tag missing."
    exit 1
fi
docker build -f "$BASEDIR"/../Dockerfile-full -t "$DOCKER_TAG":latest "$BASEDIR"/../.